### ISSUE TITLE
Fix descriptive link text error

### ISSUE THREAD

**Issue by ethan-degross** [ui-libraries/wordpress-themes#3]

**Comment by JoeyWroble** [comment]
Problem had to be solved on wp site:
When insert link in text, the word/words inserted on are counted as the link's description by lighthouse. We made a slight change from insertion on the word 'here' to on 'the book's introductory chapter' to resolve issue.

Original: "the book's introductory chapter, which explains more about my method, can be found [here] (link)."
Revision: "[the book’s introductory chapter](https://geometriesofcreation.lib.uiowa.edu/wp-content/uploads/sites/67/2020/06/BorkGEOMETRYintro.pdf) explains more about my method."
